# Generated by Django 5.0.3 on 2024-04-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('relate', models.CharField(blank=True, default='', max_length=255, verbose_name='Relate')),
                ('qualification', models.CharField(blank=True, default='', max_length=255, verbose_name='Qualification')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence')),
                ('military_officer', models.BooleanField(default=False)),
                ('spouse_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Spouse Name')),
                ('spouse_qualification', models.CharField(blank=True, default='', max_length=255, verbose_name='Qualification')),
                ('spouse_job', models.CharField(blank=True, default='', max_length=255, verbose_name='Job')),
                ('residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate', models.CharField(blank=True, choices=[('الوالد', 'الوالد'), ('الوالده', 'الوالده'), ('الجد للوالد', 'الجد للوالد'), ('الجد للوالدة', 'الجد للوالدة')], default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('nationality', models.CharField(blank=True, default='', max_length=255)),
                ('qualification', models.CharField(blank=True, default='', max_length=255, verbose_name='Qualification')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job')),
                ('military_officer', models.BooleanField(default=False)),
                ('residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence')),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate', models.CharField(blank=True, choices=[('عم', 'عم'), ('خال', 'خال')], default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('wife_name', models.CharField(blank=True, default='', max_length=255)),
                ('wife_job', models.CharField(blank=True, default='', max_length=255)),
                ('residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence')),
            ],
        ),
        migrations.CreateModel(
            name='Supports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('relate', models.CharField(blank=True, default='', max_length=255, verbose_name='Relate')),
                ('nationality', models.CharField(blank=True, default='', max_length=255, verbose_name='nationality')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('national_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='National Number')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
            ],
        ),
    ]
