# Generated by Django 4.2.4 on 2023-11-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('birth_location', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('number_of_children', models.PositiveIntegerField()),
                ('residence', models.CharField(max_length=255)),
                ('triple_digit', models.CharField(max_length=22)),
                ('mobile_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate', models.CharField(choices=[('fater_brother', 'Father Brother'), ('mother_brother', 'Mother Brother')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('job', models.CharField(max_length=255)),
                ('wife_name', models.CharField(max_length=255)),
                ('wife_job', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='database.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmohter')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('birth_location', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='database.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('job', models.CharField(max_length=255)),
                ('wife_name', models.CharField(max_length=255)),
                ('wife_job', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brothers', to='database.recruit')),
            ],
        ),
    ]
