# Generated by Django 5.0.3 on 2024-04-08 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brothers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relative',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supports',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to=settings.AUTH_USER_MODEL),
        ),
    ]
