# Generated by Django 5.0.3 on 2024-04-08 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relative',
            name='wife_job',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='wife_name',
        ),
        migrations.AddField(
            model_name='relative',
            name='spouse_job',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Spouse Job'),
        ),
        migrations.AddField(
            model_name='relative',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Spouse Name'),
        ),
        migrations.CreateModel(
            name='Current_Wife_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(choices=[('الزوجة', 'الزوجة'), ('والدها', 'والدها'), ('والدتها', 'والدتها')], max_length=255, verbose_name='Statement')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('nationality', models.CharField(blank=True, default='مصري', max_length=255)),
                ('religion', models.CharField(default='مسلم', max_length=255, verbose_name='Religion')),
                ('qualification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qualification')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job')),
                ('residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_wife_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wife_Borther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255, verbose_name='Gender')),
                ('qualification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qualification')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job')),
                ('spouse_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Spouse Name')),
                ('spouse_job', models.CharField(blank=True, default='', max_length=255, verbose_name='Spouse Job')),
                ('residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife_brothers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
