# Generated by Django 4.2.4 on 2023-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_brother_date_of_birth_alter_brother_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relate',
            field=models.CharField(blank=True, choices=[('الوالد', 'الوالد'), ('الوالده', 'الوالده'), ('الجد', 'الجد'), ('الجده', 'الجده')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relate',
            field=models.CharField(blank=True, choices=[('عم', 'عم'), ('خال', 'خال')], max_length=255, null=True),
        ),
    ]
