# Generated by Django 5.0.3 on 2024-04-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_relative_wife_job_remove_relative_wife_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relative',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='relative',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job'),
        ),
    ]
