# Generated by Django 4.2.4 on 2023-11-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_parent_relate_alter_relative_relate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='residence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='wife_job',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brother',
            name='wife_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='birth_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relate',
            field=models.CharField(blank=True, choices=[('الوالد', 'الوالد'), ('الوالده', 'الوالده'), ('الجد', 'الجد'), ('الجده', 'الجده')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='residence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='birth_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='residence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='triple_digit',
            field=models.CharField(blank=True, default='', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relate',
            field=models.CharField(blank=True, choices=[('عم', 'عم'), ('خال', 'خال')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='residence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='wife_job',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='wife_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
