# Generated by Django 5.0.3 on 2024-04-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_brother_job_alter_brother_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supports',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Date of Birth'),
        ),
    ]
