# Generated by Django 5.0.3 on 2024-04-08 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 23, 42, 58, 63032, tzinfo=datetime.timezone.utc)),
        ),
    ]
