# Generated by Django 5.0.3 on 2024-04-09 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_recruit_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 0, 22, 16, 752138, tzinfo=datetime.timezone.utc)),
        ),
    ]
