# Generated by Django 5.0.3 on 2024-04-09 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_recruit_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='arm',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Arm'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='college',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='college'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='current_job',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='current_job'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 0, 41, 58, 508743, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='education',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='email_address'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='home_phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='home_phone'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='national_number',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='National Number'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='residence',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Residence'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Unit'),
        ),
    ]
